name: Deploy subgraph

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      STUDIO_DEPLOY_KEY: ${{ secrets.STUDIO_DEPLOY_KEY }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Save package version from package.json to env.PACKAGE_VERSION
        uses: nyaa8/package-version@v1

      - name: Build and deploy
        run: yarn deploy
        env:
          VERSION: v${{ env.PACKAGE_VERSION }}
