name: Subgraphs health check

on:
  schedule:
    - cron: '8 * * * *'

jobs:
  health-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subgraph: ['in19farkt/akropolis-yearn-router']
        version: ['current', 'pending']

    steps:
      - uses: actions/checkout@v2

      - name: Get subgraph status
        id: check
        uses: akropolisio/subgraph-status-action@v1.0.2
        with:
          subgraph: ${{ matrix.subgraph }}
          version: ${{ matrix.version }}

      - name: Post errors to a Slack channel
        if: ${{ fromJSON(steps.check.outputs.hasError) }}
        uses: slackapi/slack-github-action@v1.18.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: C032HF0PA5R
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ matrix.version }} version of subgraph <https://thegraph.com/hosted-service/subgraph/${{ matrix.subgraph }}> is failed.\n\n• Error code: `${{ steps.check.outputs.errorCode }}`\n• Message:\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(steps.check.outputs.message) }}
                  }
                }
              ]
            }
